apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-company
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /hello
    - uri:
        exact: /long        
    route:
    - destination:
        host: hello-world-company.kube-public.svc.cluster.local
        port:
          number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-company
  namespace: kube-public
  labels:
    app: hello-world-company
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hello-world-company
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-company
  namespace: kube-public
  labels:
    app: hello-world-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-company
      tier: web
  template:
    metadata:
      labels:
        app: hello-world-company
        tier: web
    spec:
      containers:
      - name: hello-world
        image: gcr.io/a506-till/hello-company:with-gs-v1
        ports:
        - containerPort: 8080          